### ISSUE TITLE
DCAT : ModuleNotFoundError: No module named 'dcat.dcat_time_models'

### ISSUE THREAD

**Issue by priya-gitTest** [Health-RI/SeMPyRO#10]
![image](https://github.com/Health-RI/SeMPyRO/assets/21082240/47305274-a0b0-496d-8464-505e8be78709)
![image](https://github.com/Health-RI/SeMPyRO/assets/21082240/acee1e00-176c-43b1-a493-2d365d181bd6)
![image](https://github.com/Health-RI/SeMPyRO/assets/21082240/9fba25c1-735d-42f7-8f41-f8d00275526c)

Error when running this notebook : https://github.com/Health-RI/SeMPyRO/blob/main/docs/Usage_example_time_models.ipynb

**Comment by Markus92** [comment]
References to `dcat.dcat_time_models` need to be changed to `sempyro.time.dcat_time_models`

Class `Temporal` is now called `PeriodOfTime`

Class `GeneralDateTimeDescription` has mandatory property `hasTRS` (see [here](https://www.w3.org/TR/owl-time/#time:hasTRS)). Would need to investigate what the correct range is for this.

Unfortunately time on our end to work on this is limited in the short-term but we're open to pull requests.

**Comment by priya-gitTest** [comment]
Thanks for the update. I will try and workout, how I can help you , by fixing this.

**Comment by priya-gitTest** [comment]
Thanks. It works now !!!
